import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { X, Minus, Plus, CreditCard, CheckCircle, AlertCircle, Loader2, Smartphone, Mail, User, Ticket, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { formatCurrency, isValidKenyanPhone, isValidEmail } from '@/utils/helpers';
import { API_BASE_URL } from '@/utils/constants';